version: '3'

services:
  #db
  db:
    image: mysql:5.7
    volumes: 
  #    - ${DB_VOLUME}:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/migration.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #site
  wordpress:
    ports:
      - 80:80
    depends_on:
      - db
    image: wordpress:latest
    restart: unless-stopped
    volumes: 
      - ./site/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./site/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./site/wp-content/themes:/var/www/html/wp-content/themes
    #  - ./site/wp-config.php:/var/www/html/wp-config.php
    #  - ./site:/var/www/html/
    #  - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    
  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT_3306_TCP_ADDR: db
      
#   nginx:
#     image: nginx
#     depends_on:
#         - db
#     restart: unless-stopped
#     ports:
#       - 80:80
#       - 443:443
#     volumes:
#     #  - ./wordpress:/etc/nginx/conf.d
#     - ./nginx_config_content:/etc/nginx/conf.d/nginx_config_content